remote_theme: pages-themes/slate@v0.2.0
theme: jekyll-theme-slate
title: Hompage Mark Dirksen
description: Contains Data Science and / or coding related content.
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
